#!/usr/bin/env node

const CuratedLinter = require('..')

// eslint-disable-next-line no-new
new CuratedLinter(() => ({
  name: 'linter',
  formatter: results => JSON.stringify(results),
  defaultFiles: ['no-unused-expressions.js'],
  CLIEngineOptions: {
    baseConfig: {
      extends: 'standard'
    }
  }
}))
